# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Example' do
    pod 'StandardPaths', :path => '../../'
end

target 'ExampleNoSwizzle' do
    pod 'StandardPaths/NoSwizzle', :path => '../../'
end

